create table if not exists public.goal_contributions (
  id bigint generated by default as identity primary key,
  goal_id bigint not null references public.goals(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  amount numeric not null check (amount > 0),
  note text,
  created_at timestamptz not null default now()
);

create index if not exists goal_contributions_goal_id_idx
  on public.goal_contributions (goal_id, created_at desc);

alter table public.goal_contributions enable row level security;

drop policy if exists "Users can manage own goal contributions" on public.goal_contributions;
create policy "Users can manage own goal contributions"
  on public.goal_contributions
  for all
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
